#! /bin/bash

EVAL=rewrite

# parse the arguments
for i in $*
do
    case $i in
	--eval)
	    EVAL=$i
	;;
	*)
# @todo: check if file is not found. Should not be necessary

            FILE=$i
	;;
    esac
done


if [ $# -lt 1 ]; then
    echo "USAGE: $0 --eval filename";
    exit 1;
fi

# store the rewritten query in tempfiles/
# RESTMP=`mktemp -t xsparql_result_XX`
$RESTMP=$FILE.out

cat $FILE | xsparqler.py 2>/dev/null > $RESTMP

RETCODE=$?

# if the parse failed return the original query
if [ $RETCODE -ne 0 ]; then
    cat $FILE;
else
    # otherwise evaluate or print the rewritten query
    if [ $EVAL == "--eval" ]; then
	xqilla $RESTMP;
	RETCODE=$?;
    else
	cat $RESTMP;
    fi
fi

# rm -f $RESTMP

exit $RETCODE
